### ISSUE TITLE
Initial Integration with Gemini

### ISSUE THREAD

**Issue by brucearctor** [pixeltable/pixeltable#299]
See: https://ai.google.dev/api?lang=python

Might warrant sub-issues as Gemini does alot.

**Comment by pierrebrunelle** [comment]
@brucearctor could you share more about the use cases you are trying to cover with these Google integrations so we can discuss prioritizing them accordingly? Some are fairly easy and others require scoping.

For instance, here's how the integration with Mistral AI was done:
- Implementation: https://github.com/pixeltable/pixeltable/blob/main/pixeltable/functions/mistralai.py
- Test: https://github.com/pixeltable/pixeltable/blob/main/tests/functions/test_mistralai.py

**Comment by pierrebrunelle** [comment]
> I imagined one of the best ways to get to know intricacies of pixeltable would be by contributing something. I am a GDE [ https://developers.google.com/community/experts ], so helping with a Google integration wouldn't be a bad place to spend some cycles.
> [...]  these things in https://github.com/pixeltable/pixeltable/tree/main/pixeltable/functions [ and the associated tests ] do appear as straightforward enough wrappers. So, agreed that many shouldn't be too big a lift.

It'd be indeed. These API Inference integrations are a great way to get started and we usually always build a notebook alongside it that lives in the tutorials section, e.g. https://github.com/pixeltable/pixeltable/blob/main/docs/release/tutorials/working-with-mistralai.ipynb

**Comment by aaron-siegel** [comment]
Shipped in Pixeltable v0.2.27.

**Comment by brucearctor** [comment]
Relevant PR:  https://github.com/pixeltable/pixeltable/pull/391
