### ISSUE TITLE
Some links are broken in Pixeltable Docs

### ISSUE THREAD

**Issue by denise-k** [pixeltable/pixeltable#329]
Not necessarily a comprehensive list, just some ones I saw.
- In [Pixeltable Basics](https://docs.pixeltable.com/docs/pixeltable-basics), the link to Getting Started with Pixeltable is stale.
- In [Tables and Data Operations](https://docs.pixeltable.com/docs/tables-and-data-operations), the links to Pixeltable Fundamentals, Computed Columns, and Unstructured Data are stale.
- In [Computed Columns](https://docs.pixeltable.com/docs/computed-columns), the 2nd link to Tables and Data Operations is stale (1st is fine).
- In [UDFs](https://docs.pixeltable.com/docs/user-defined-functions-udfs), the link to Type System is stale.
- In [Object Detection in Videos](https://docs.pixeltable.com/docs/object-detection-in-videos), the link to
Pixeltable Basics is stale
- In [OpenAI tutorial](https://docs.pixeltable.com/docs/working-with-openai), the link to Pixeltable Basics is stale.

**Comment by pierrebrunelle** [comment]
Thanks for reporting this. All fixed.
