### ISSUE TITLE
get rid of tqdm warnings in notebooks

### ISSUE THREAD

**Issue by mkornacker** [pixeltable/pixeltable#80]
Right now, you see this in response to 'import pixeltable':
/home/marcel/pixeltable/pixeltable/exec/expr_eval_node.py:6: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

**Comment by aaron-siegel** [comment]
Fixed by PR #100.
